# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stuart Labs 
email: stuart@stuartwoodward.com 
description: > # this means to ignore newlines until "baseurl:"
  Some public notes on things that I want to remember having looked at this month. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stuartcw.com" # the base hostname & protocol for your site
twitter_username: stuartcw 
github_username: stuartcw 

# Build settings
markdown: kramdown
